### PR TITLE
Batcheffect bugfix

### PR DESCRIPTION
**Pull request by WackerO**
This PR fixes an error that appears when using the batcheffect option.

## PR checklist

//TODO: Change nf-core? In "If necessary, also...", this does not make much sense, maybe just delete?

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/rnadeseq/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/rnadeseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by WackerO** [comment]
Does it make sense to add another test config with batch effect enabled? If so, will have to check what needs to be changed in the input data

**Comment by ggabernet** [comment]
yes, it's be great to add a test profile with this batch correction being tested :)

**Comment by WackerO** [comment]
Please do not merge yet even if the tests succeed

**Comment by WackerO** [comment]
Can be merged!

**Review by ggabernet — APPROVED** [review]
Looks good to me!

**Pull request merged**
